### ISSUE TITLE
transfer to r-hub org?

### ISSUE THREAD

**Issue by maelle** [r-hub/cranatgh#10]
And once it's done, I can create the pkgdown website :-)

**Comment by maelle** [comment]
After transfer, what should be the new URLs for

* this repo 
* the cran GitHub organization?

Both point to r-pkg.org. Maybe they could point to the `#cranatgh` part of the docs? Cf https://github.com/r-hub/docs/pull/10

**Comment by maelle** [comment]
But that's probably not a good URL to use to verify the GitHub organization (and verifying it would be nice), maybe cranatgh.r-hub.io could exist, be used as URL for the repo + the org, and redirect to the part of the docs related to cranatgh?

**Comment by gaborcsardi** [comment]
We can transfer, but I don't think this needs a pkgdown site, it is not a user facing package.

**Comment by maelle** [comment]
Ok so I'd just add some info in particular from #9 to the README :-)
