### ISSUE TITLE
missed package update?

### ISSUE THREAD

**Issue by bastistician** [r-hub/cranatgh#14]
Dear Gábor,
I was told that https://github.com/cran/surveillance is outdated.
It holds version 1.17.3 but CRAN has version 1.18.0 already since 2020-03-19.
Is there anything I can do on package maintainer side? Pinging the jenkins URL referenced in https://github.com/r-hub/cranatgh/issues/9#issuecomment-488239917 gives a 502 bad gateway for me, but I may be doing something wrong.
Thank you!

**Comment by gaborcsardi** [comment]
I don't know why it was skipped. Added now.
