### ISSUE TITLE
Disable Issues on a mirrored repositories?

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-hub/cranatgh#18]
I guess you already thought about it, but if not, would it be feasible to disable 'Issues' for all repositories on <https://github.com/cran/> to avoid people from submitting issues, e.g. https://github.com/search?q=org%3Acran&type=issues?

I scanned <https://docs.github.com/en/rest/reference> but could _not_ find an endpoint for ['Disabling Issues'](https://docs.github.com/en/enterprise-cloud@latest/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/disabling-issues) vie the REST API.  Maybe that answers my question - doing it by hand for ~20,000 would be too much work.

**Comment by gaborcsardi** [comment]
It is good to have the issues open, because if people create an issue here, they'll get a message that points them to the right direction. That is better than them not finding any place to report issues.

**Comment by HenrikBengtsson** [comment]
I see.  Thxs.
