### ISSUE TITLE
Package {cookies} not updated

### ISSUE THREAD

**Issue by jonthegeek** [r-hub/cranatgh#19]
I vanity-searched my latest package in [the CRAN mirror](https://github.com/search?q=org%3Acran+cookies), and noticed that it's out-of-date. An update was published on CRAN on [2023-01-10](https://cran.r-project.org/package=cookies), but the crangh mirror has the previous version.

I don't see any indication in the [actions here](https://github.com/r-hub/cranatgh/actions?page=7) about anything failing on that day, so I'm not sure what made it get missed. 

I assume there are other packages with issues (or I was incredibly lucky/unlucky, depending how you look at it), but I'm not sure where to start in order to fix the issue. I'm not even 100% certain this is the correct repository to put this issue in.

**Comment by gaborcsardi** [comment]
Fixed.
