### ISSUE TITLE
Bug with committing case sensitive filename changes.

### ISSUE THREAD

**Issue by jeroen** [r-hub/cranatgh#25]
Example:

```r
git clone https://github.com/cran/ggplot2
R CMD build ggplot2
```

I think the bug is that ggplot2 [renamed some files](https://github.com/tidyverse/ggplot2/pull/5221/files) from `.r` to `.R` but the bot did not commit those renames because it runs on a case insensitive file system.

**Comment by gaborcsardi** [comment]
The auto-update runs on a case sensitive file system, but I update some packages manually from macOS, which caused this issue.

**Comment by gaborcsardi** [comment]
OK, I fixed ggplot2 manually now. Unfortunately I don't see a way to make the update work from a case insensitive fs, but I'll do manual updates from a Linux container in the future...

IDK if there is an easy way to detect a similar issue for other packages, but I didn't do a lot of manual updates, so hopefully there isn't many more.
