### ISSUE TITLE
mgcv not up-to-date

### ISSUE THREAD

**Issue by hriebl** [r-hub/cranatgh#8]
The mgcv package is not up-to-date on GitHub. More specifically, it's version 1.8-7 on GitHub (https://github.com/cran/mgcv) but version 1.8-24 on CRAN (https://www.r-pkg.org/pkg/mgcv, https://cran.r-project.org/package=mgcv).

**Comment by hriebl** [comment]
@gaborcsardi, just wanted to ask if this was the right place to report this issue. Did you receive a notification?

**Comment by gaborcsardi** [comment]
Yes, will fix soon.

**Comment by hriebl** [comment]
Seems like this is fixed now! \o/

**Comment by StaffanBetner** [comment]
It is an issue once again.

**Comment by gaborcsardi** [comment]
Yeah. I don't know what I did before, but my mirror script now fails for mgcv, will fix in a minute.

**Comment by StaffanBetner** [comment]
Same problem once again. New version, but isn't mirrored. Something seems to be strange with mgcv :)

**Comment by gaborcsardi** [comment]
This is a different issue, now, all updates failed, thanks for letting me know:
https://github.com/r-hub/cranatgh/runs/1924045736?check_suite_focus=true
